package net.spikesync.devping;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.junit.jupiter.api.Test;
import org.junit.jupiter.api.condition.EnabledIf;
import org.junit.runner.RunWith;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.test.context.junit4.SpringRunner;
import org.springframework.context.ApplicationContext;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.tuple;


@RunWith(SpringRunner.class)
@SpringBootTest(classes = DevPingApplication.class)
public class DevPingApplicationTest {

    private static final Logger logger = LoggerFactory.getLogger(DevPingApplication.class);

	@Autowired
	private SilverCloud sc;
	@Value("${test-silvercloud-scnodes}")
	private String testingEnabled;


    @Test
    @EnabledIf("testingEnabled")
    public void silverCloudTest(ApplicationContext context) {
 
 
    	assertThat(sc.getScNodes())
		.extracting("nodeName", "ipAddress").contains(
				tuple("SURFIE","192.168.50.100"),
				tuple("CAPTUW","192.168.50.104"),
				tuple("THORFW","192.168.50.107"),
				tuple("LOKIFS","192.168.50.110"),
				tuple("SCARFS","192.168.50.113"),
				tuple("HYDRFS","192.168.50.116"),
				tuple("ASGAFS","192.168.50.119")
				);
    }
    
    @SuppressWarnings("unused") // This method is used by JUnit 5 @EnabledIf, i.e., it is generated by JUnit and not used by methods of net.spikesync.devping.DevPingApplicationTest
	private boolean testingEnabled() {
    	logger.debug("In method DevPingApplicationTest.testingEnabled() with this.testingEnabled = " + this.testingEnabled);
    	if (this.testingEnabled.equals("true") || this.testingEnabled.equals("TRUE")) 
    		return Boolean.TRUE;
    	else return Boolean.FALSE; 
    }
}